version: "3.3"

networks:
  public: {}

volumes:
  prometheus_data: {}
  prometheus_config:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  prometheus:
    image: prom/prometheus:v2.19.0
    ports:
      - 9090:9090
    networks:
      - public
    volumes:
      - prometheus_data:/prometheus
      - prometheus_config:/fragments/
      - ${PWD}/prometheus-server/config/prometheus.json:/etc/prometheus/prometheus.json
      - ${PWD}/prometheus-server/config/grafana.json:/etc/prometheus/grafana.json
    command:
      - '--config.file=/fragments/complete/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  config-concat:
    image: deanwilson/promconf-concat:0.1.0
    volumes:
      - prometheus_config:/fragments/
      - ${PWD}/prometheus-server/config/base_prometheus.yml:/base_prometheus.yml
